[package]
name = "image_mover"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.56", features = ["Win32_UI_Shell", "Win32_System_Com", "Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }
rayon = "1.8"

[build-dependencies]
embed-resource = "2.4"
